
export const BIRD_SOUNDS = [
  './assets/birds/mexican_parrot.mp3',
  './assets/birds/chicken_laying_egg.mp3',
  './assets/birds/lark.mp3',
  './assets/birds/lorie.mp3',
  './assets/birds/canary.mp3',
  './assets/birds/owl.mp3',
  './assets/birds/rooster.mp3',
  './assets/birds/blackbird.wav',
  './assets/birds/canary.wav',
  './assets/birds/crow.wav',
  './assets/birds/japanese_crow.mp3',
  './assets/birds/japanese_crow.wav',
  './assets/birds/kukoo.wav',
  './assets/birds/lark.mp3',
  './assets/birds/lorie.mp3',
  './assets/birds/nightingale.wav',
  './assets/birds/nightingale2.wav',
  './assets/birds/nightingale2.wav',
  './assets/birds/parrot.wav',
  './assets/birds/parrothello.wav',
  './assets/birds/titmouse.wav',
  './assets/birds/unknown_australian_bird.wav',
  './assets/birds/wakerone.mp3',
  './assets/birds/wing.ogg'
];
